---
- name: Ansible Playbook
  hosts: webservers
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - gnupg

    - name: Add MongoDB APT key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.0.asc
        state: present

    - name: Add MongoDB APT repository
      apt_repository:
        repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/4.0 multiverse"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Copy new helloworld files
      copy:
        src: files/helloworld/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0644"
        recurse: yes

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
